[package]
name = "hr-id"
version = "0.1.0"
authors = ["haydn@tinychain.net"]
edition = "2018"
description = "A human-readable unique ID which supports Unicode"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/haydnv/tinychain.git"

[features]
all = ["uuid"]

[dependencies]
safecast = "0.1"
regex = "1.5"
uuid = { version = "0.8", optional = true }
